### ISSUE TITLE
Thread-safety for parallel calculations and reading results

### ISSUE THREAD

**Issue by mpjurkowski** [PMeira/dss_sharp#10]
Hi, 

does the dss_sharp extension support multithreaded access to OpenDSS for parallel, separate circuits solve and reading element results? I know that the basic OpenDSS COM server doesn't.

Regards, 
Maciej

**Comment by PMeira** [comment]
Not yet, but most of the work for that is already done for the base library (DSS C-API) -- not released, still under testing but no major surprises so far. It's a different implementation that supports completely independent OpenDSS instances in the same process, which can be used in separate threads (you'd only need manual locking if you're sharing the same instance across multiple threads, etc.).

We should have a new release of DSS Sharp supporting both this new version of DSS C-API and error-to-exception mapping by the end of the year.

**Comment by PMeira** [comment]
Finally merged!
